import { db } from "../../../db";
import { applyBuff } from "../../buffService";
import type { SpellHandlerResult } from "../../spellHandlers/types";
import type { SpellTalentHandler,TalentConfig } from "../types";
const n=(c:TalentConfig,k:string,d=0)=>{const v=Number(c[k]);return Number.isFinite(v)?v:d;};
const cfg=(c:any)=>{if(!c.spell.rank_config||typeof c.spell.rank_config!=="object")c.spell.rank_config={};return c.spell.rank_config as Record<string,any>;};
const target=(c:any,r?:any)=>Number(r?.healedTargetId??c.targetPlayerId??c.playerId);
const maxhp=(c:any,r?:any)=>Math.max(1,Number(r?.healedTargetMaxHP??c.maxTargetHP??c.maxPlayerHP??c.targetPlayer?.maxhp??c.player?.maxhp??1));
const living=(c:any)=>{const a=(c.allies??[]).filter((x:any)=>Number(x.hp)>0);return a.length?a:[{playerId:c.playerId,hp:c.currentPlayerHP??c.player?.hpoints??1,maxHp:c.maxPlayerHP??c.player?.maxhp??1,stats:c.player}];};
async function shield(pid:number,amount:number,seconds:number,source:string){if(amount>0)await db.query(`INSERT INTO player_shields(player_id,max_absorb,remaining_absorb,expires_at,source) VALUES(?,?,?,DATE_ADD(NOW(3),INTERVAL ? SECOND),?) ON DUPLICATE KEY UPDATE max_absorb=VALUES(max_absorb),remaining_absorb=VALUES(remaining_absorb),expires_at=VALUES(expires_at)`,[pid,amount,amount,seconds,source]);}
async function healPct(pid:number,max:number,pct:number){const amount=Math.floor(max*pct/100);await db.query(`UPDATE players SET hpoints=LEAST(?,hpoints+?) WHERE id=?`,[max,amount,pid]);return amount;}
async function status(pid:number,key:string,value:number,charges:number,seconds:number,source:string){await db.query(`INSERT INTO player_status_effects(player_id,effect_key,value,charges,expires_at,source) VALUES(?,?,?,?,DATE_ADD(NOW(3),INTERVAL ? SECOND),?) ON DUPLICATE KEY UPDATE value=VALUES(value),charges=VALUES(charges),expires_at=VALUES(expires_at)`,[pid,key,value,charges,seconds,source]);}
export const bloodweaverTalentHandlers:Record<string,SpellTalentHandler>={
 bloodweaver_crimson_overflow:{async afterCast(c,r){const amount=Math.min(Math.floor(maxhp(c,r)*n(c.talent.config,"capMaxHpPercent",10)/100),Math.max(0,Number(r.overhealing)||0));await shield(target(c,r),amount,8,`talent:${c.talent.id}`);return{...r,overflowShield:amount};}},
 bloodweaver_desperate_weaving:{beforeCast(c){const hp=Number(c.currentTargetHP??c.currentPlayerHP??0),max=maxhp(c);if(hp/max<n(c.talent.config,"healthThresholdPercent",40)/100)c.spell.heal=Math.round(Number(c.spell.heal)*(1+n(c.talent.config,"healingPercent",35)/100));}},
 bloodweaver_quickened_blood:{afterCast(c,r){return{...r,targetGaugeGain:(Number(r.targetGaugeGain)||0)+n(c.talent.config,"gaugeGain",12),targetGaugePlayerId:target(c,r)};}},
 bloodweaver_perfect_conservation:{afterCast(c,r){return Number(r.overhealing)>0?r:{...r,manaRestored:(Number(r.manaRestored)||0)+Math.floor(c.castState.manaCost*n(c.talent.config,"refundPercent",30)/100)};}},
 bloodweaver_immediate_pulse:{async afterCast(c,r){const tick=Number(r.healingPerTick??r.vitalThreadHealingPerTick)||0;if(tick)await db.query(`UPDATE players SET hpoints=LEAST(?,hpoints+?) WHERE id=?`,[maxhp(c,r),tick,target(c,r)]);return{...r,healing:(Number(r.healing)||0)+tick};}},
 bloodweaver_vital_urgency:{modifySpell(c){const x=cfg(c);x.hotLowHealthThreshold=n(c.talent.config,"healthThresholdPercent",50);x.hotLowHealthBonus=n(c.talent.config,"healingPercent",30);},async afterCast(c,r){await status(target(c,r),"hot_low_health_bonus",n(c.talent.config,"healthThresholdPercent",50)*1000+n(c.talent.config,"healingPercent",30),99,Number(c.spell.dot_duration)+2,`hot:spell:${c.spell.id}`);return r;}},
 bloodweaver_unbroken_thread:{modifySpell(c){const x=cfg(c);x.hotRefreshPercent=n(c.talent.config,"refreshPercent",50);x.hotRefreshes=1;},async afterCast(c,r){await status(target(c,r),"hot_refresh",n(c.talent.config,"refreshPercent",50)*1000+Number(c.spell.dot_duration),1,Number(c.spell.dot_duration)+2,`hot:spell:${c.spell.id}`);return r;}},
 bloodweaver_pulsing_momentum:{modifySpell(c){cfg(c).hotGaugePerTick=n(c.talent.config,"gaugeGain",3);},async afterCast(c,r){await status(target(c,r),"hot_gauge_per_tick",n(c.talent.config,"gaugeGain",3),99,Number(c.spell.dot_duration)+2,`hot:spell:${c.spell.id}`);return r;}},
 bloodweaver_echoing_bond:{async afterCast(c,r){await status(target(c,r),"sanguine_echo_to_caster",n(c.talent.config,"selfHealPercent",30),99,Number(c.spell.buff_duration),`bond:${c.playerId}`);return r;}},
 bloodweaver_bloodguard_bond:{async afterCast(c,r){await applyBuff(target(c,r),"damage_reduction",n(c.talent.config,"reductionPercent",12),Number(c.spell.buff_duration),`talent:${c.talent.id}`);return r;}},
 bloodweaver_empowering_bond:{async afterCast(c,r){await applyBuff(target(c,r),"damage_dealt_pct",n(c.talent.config,"damagePercent",12),Number(c.spell.buff_duration),`talent:${c.talent.id}`);return r;}},
 bloodweaver_shared_vitality:{async afterCast(c,r){await status(target(c,r),"sanguine_shared_vitality",n(c.talent.config,"sharedHealPercent",20),99,Number(c.spell.buff_duration),`bond:${c.playerId}`);return r;}},
 bloodweaver_sanguine_shield:{async afterCast(c,r){const amount=Math.min(Math.floor(maxhp(c,r)*n(c.talent.config,"capMaxHpPercent",15)/100),Math.max(0,Number(r.overhealing)||0));await shield(target(c,r),amount,8,`talent:${c.talent.id}`);return{...r,overflowShield:amount};}},
 bloodweaver_predatory_drain:{beforeCast(c){const hp=Math.max(0,Number(c.enemy?.hp)||0),max=Math.max(1,Number(c.enemy?.maxhp)||1);if(hp/max<n(c.talent.config,"healthThresholdPercent",35)/100)c.spell.damage=Math.round(Number(c.spell.damage)*(1+n(c.talent.config,"damagePercent",40)/100));}},
 bloodweaver_distributed_vitality:{async afterCast(c,r){const ally=living(c).filter((a:any)=>Number(a.playerId)!==c.playerId).sort((a:any,b:any)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],amount=Number(r.healing)||0;if(!ally||amount<=0)return r;await db.query(`UPDATE players SET hpoints=GREATEST(1,hpoints-?) WHERE id=?`,[amount,c.playerId]);await db.query(`UPDATE players SET hpoints=LEAST(?,hpoints+?) WHERE id=?`,[ally.maxHp,amount,ally.playerId]);return{...r,healedTargetId:Number(ally.playerId),log:`${r.log??""} 🩸 Distributed Vitality transfers ${amount} healing to ${ally.name??"the most injured ally"}!`};}},
 bloodweaver_essence_recovery:{afterCast(c,r){return{...r,manaRestored:(Number(r.manaRestored)||0)+Math.floor((Number(r.damage)||0)*n(c.talent.config,"damageToManaPercent",15)/100)};}},
 bloodweaver_crimson_surge:{async afterCast(c,r){let total=0;for(const a of living(c)){const [[hot]]:any=await db.query(`SELECT healing FROM player_hots WHERE player_id=? AND source=? AND expires_at>NOW(3) LIMIT 1`,[a.playerId,`spell:${c.spell.id}`]);const amount=Math.max(0,Number(hot?.healing)||0);if(amount){await db.query(`UPDATE players SET hpoints=LEAST(?,hpoints+?) WHERE id=?`,[a.maxHp,amount,a.playerId]);total+=amount;}}return{...r,healing:(Number(r.healing)||0)+total};}},
 bloodweaver_emergency_renewal:{modifySpell(c){const x=cfg(c);x.groupHotLowHealthThreshold=n(c.talent.config,"healthThresholdPercent",40);x.groupHotLowHealthBonus=n(c.talent.config,"healingPercent",35);},async afterCast(c,r){for(const a of living(c))await status(a.playerId,"hot_low_health_bonus",n(c.talent.config,"healthThresholdPercent",40)*1000+n(c.talent.config,"healingPercent",35),99,Number(c.spell.dot_duration)+2,`hot:spell:${c.spell.id}`);return r;}},
 bloodweaver_renewing_momentum:{modifySpell(c){cfg(c).groupHotGaugePerTick=n(c.talent.config,"gaugeGain",3);},async afterCast(c,r){for(const a of living(c))await status(a.playerId,"hot_gauge_per_tick",n(c.talent.config,"gaugeGain",3),99,Number(c.spell.dot_duration)+2,`hot:spell:${c.spell.id}`);return r;}},
 bloodweaver_endless_circulation:{modifySpell(c){const x=cfg(c);x.groupHotRefreshPercent=n(c.talent.config,"refreshPercent",50);x.groupHotRefreshes=1;},async afterCast(c,r){for(const a of living(c))await status(a.playerId,"hot_refresh",n(c.talent.config,"refreshPercent",50)*1000+Number(c.spell.dot_duration),1,Number(c.spell.dot_duration)+2,`hot:spell:${c.spell.id}`);return r;}},
 bloodweaver_controlled_sacrifice:{modifySpell(c){cfg(c).healthCostReductionPercent=n(c.talent.config,"healthCostReductionPercent",40);}},
 bloodweaver_life_beyond_death:{async afterCast(c,r){await status(target(c,r),"bloodweaver_death_protection",n(c.talent.config,"revivePercent",40),n(c.talent.config,"charges",1),n(c.talent.config,"durationSeconds",10),`talent:${c.talent.id}`);return r;}},
 bloodweaver_overflowing_transfusion:{async afterCast(c,r){const cap=n(c.talent.config,"capMaxHpPercent",20),over=Math.max(0,Number(r.overhealing)||0),tAmount=Math.min(Math.floor(maxhp(c,r)*cap/100),over),cMax=Math.max(1,Number(r.casterMaxHP??c.maxPlayerHP??c.player?.maxhp));await shield(target(c,r),tAmount,10,`talent:${c.talent.id}:target`);await shield(c.playerId,Math.min(Math.floor(cMax*cap/100),over),10,`talent:${c.talent.id}:caster`);return r;}},
 bloodweaver_crimson_communion:{async afterCast(c,r){let total=0;for(const a of living(c).filter((x:any)=>Number(x.playerId)!==target(c,r)))total+=await healPct(a.playerId,a.maxHp,n(c.talent.config,"maxHpPercent",20));return{...r,healing:(Number(r.healing)||0)+total};}},
 bloodweaver_reclaimed_essence:{async afterCast(c,r){const sec=n(c.talent.config,"durationSeconds",10),max=Math.max(1,Number(r.casterMaxHP??c.maxPlayerHP??c.player?.maxhp));await applyBuff(c.playerId,"damage_reduction",n(c.talent.config,"reductionPercent",30),sec,`talent:${c.talent.id}`);const total=Math.floor(max*n(c.talent.config,"healMaxHpPercent",10)/100),tick=Math.max(1,Math.floor(total/5));await db.query(`INSERT INTO player_hots(player_id,healing,tick_interval,next_tick_at,expires_at,source,display_name) VALUES(?,?,2,DATE_ADD(NOW(3),INTERVAL 2 SECOND),DATE_ADD(NOW(3),INTERVAL ? SECOND),?,?)`,[c.playerId,tick,sec,`talent:${c.talent.id}`,"Reclaimed Essence"]);return r;}}
};
